spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yourMail@gmail.com
    password: appPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
